version: '3.7'

services:
  order-service:
    image: manishnauty/order-service:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    