apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: manishnauty/order-service:0.0.1-SNAPSHOT
        name: order-service
        ports:
        - containerPort: 8080
      restartPolicy: Always
