apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    io.kompose.service: order-service
