version: '3.7'

services:
  user-service:
    image: manishnauty/user-service:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      UDB_HOSTNAME: mysql
      UDB_PORT: 3306
      UDB_DB_NAME: user
      UDB_USERNAME: root
      UDB_PASSWORD: root
    networks:
      - miservice-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: user
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - miservice-network  
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  miservice-network: