apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    protocal: TCP
  selector:
    app: mysql
  sessionAfinity: None

