apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: UDB_DB_NAME
#          value: user
          valueFrom:
            configMapKeyRef:
               key: UDB_DB_NAME
               name: microservice-config
        - name: UDB_HOSTNAME
#          value: mysql
          valueFrom:
            configMapKeyRef:
               key: UDB_HOSTNAME
               name: microservice-config
        - name: UDB_PASSWORD
#          value: root
          valueFrom:
            secretKeyRef:
               key: UDB_PASSWORD
               name: microservice-secret
        - name: UDB_PORT
#          value: "3306"
          valueFrom:
            configMapKeyRef:
               key: UDB_PORT
               name: microservice-config
        - name: UDB_USERNAME
#          value: root
          valueFrom:
            configMapKeyRef:
               key: UDB_USERNAME
               name: microservice-config
        image: manishnauty/user-service:0.0.1-SNAPSHOT
        name: user-service
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
           requests:
              #cpu: 200m
              memory: 512Mi
           limits:
              #cpu: 200m 
              memory: 1024Mi
        readinessProbe:
           httpGet:
              path: /
              port: liveness-port
           failureThreadhold: 5
           initialDelaySeconds: 60
           periodSeconds: 10
        livenessProbe:
           httpGet:
              path: /
              port: liveness-port
           failureThreadhold: 5
           initialDelaySeconds: 60
           periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
