version: '3.7'

services:
  user-service:
    image: manishnauty/user-order-aggregation-service:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always