apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: user-order-aggreagation-service
  name: user-order-aggregation-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-order-aggregation-service
    spec:
      containers:
      - image: manishnauty/user-order-aggregation-service:0.0.1-SNAPSHOT
        name: user-order-aggregation-service
        env:
          - name: ORDER_SERVICE_URI
            value: http://order-service
          - name: USER_SERVICE_URI
            value: http://user-service
        ports:
        - containerPort: 8080
      restartPolicy: Always
